name       : entangle
version    : '1.0'
release    : 4
source     :
    - http://entangle-photo.org/download/sources/entangle-1.0.tar.xz : 6937433ebb9ea91116ea71363fdfbb214ea52b7c168900d453c3156230027d36
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Tethered camera control and capture
description: |
    Entangle provides a graphical interface for “tethered shooting”, aka taking photographs with a digital camera completely controlled from the computer
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gexiv2)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libraw)
    - itstool
    - gnome-icon-theme-symbolic
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
