name       : entangle
version    : 0.7.1
release    : 1
source     :
    - https://www.entangle-photo.org/download/sources/entangle-0.7.1.tar.gz : 3e330e833066fcedb2290eb844de304af8755c5ed9ff1e5b862932e3feef4a6e
license    : GPL-3.0
component  : multimedia.graphics
summary    : Tethered camera control and capture
description: |
    Entangle provides a graphical interface for “tethered shooting”, aka taking photographs with a digital camera completely controlled from the computer
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gexiv2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libraw)
    - itstool
    - gnome-icon-theme-symbolic
    - yelp-tools
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
