name       : entangle
version    : '3.0'
release    : 17
source     :
    - https://gitlab.com/entangle/entangle/-/archive/v3.0/entangle-v3.0.tar.bz2 : bd0ecd89bd68db59f3c43bfb353f7f86f606c07836ef381b8c010d465b676efd
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Tethered camera control and capture
description: |
    Entangle provides a graphical interface for “tethered shooting”, aka taking photographs with a digital camera completely controlled from the computer
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gexiv2)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libgphoto2)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(libraw)
    - itstool
    - gnome-icon-theme-symbolic
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/fix-build-with-new-meson.patch
    %meson_configure
build      : |
    %ninja_build -j1
install    : |
    %ninja_install
